import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navigation from "../components/navigation/navbar";
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dave's Page",
  description: "Generated by Dave",
};

export default function RootLayout({
  children,
}:{
  children: React.ReactNode;
}) {
  //Add <Navigation /> above {children} to return top bar
  return (
    <html lang="en">
      <body /*className={`${geistSans.variable} ${geistMono.variable} antialiased`}*/>

        {children}
      </body>
    </html>
  );
}
