import type { Metadata } from "next";

import "./globals.css"

export const metadata: Metadata = {
  title: "David Maguire",
  description: "Generated by David Maguire",
};

export default function RootLayout({
  children,
}:{
  children: React.ReactNode;
}) {
  //Add <Navigation /> above {children} to return top bar
  return (
    <html lang="en">
      <body /*className={`${geistSans.variable} ${geistMono.variable} antialiased`}*/>

        {children}
      </body>
    </html>
  );
}
